# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nazwa restauracji')),
                ('address', models.CharField(max_length=255, verbose_name='adres restauracji')),
                ('phone_number', models.CharField(max_length=16, verbose_name='numer telefonu')),
                ('order_time_start', models.TimeField(verbose_name='od godziny:')),
                ('order_time_end', models.TimeField(verbose_name='do godziny:')),
            ],
        ),
    ]
